### ISSUE TITLE
only generate 2 words

### ISSUE THREAD

**Issue by TuuSiwei** [modelscope/FunASR#963]
I used the code provided in the tutorial but only generated the first two Chinese characters of the audio
why?

**Comment by lyblsgo** [comment]
Please provide detailed information so that we can reproduce the issue. If we cannot reproduce it, it means the problem cannot be resolved.

**Comment by tsw123678** [comment]
It seems that the model , 'damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online,' is able to successfully recognize test recordings provided by you and other synthesized audio, but when i try to recognize my own recorded audio, it only recognizes the first two words.

later,i use the model:model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
and solve the question.


but why it?
&nbsp;


yy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yabin ***@***.***&gt;; 
发送时间: 2023年9月25日(星期一) 上午10:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba-damo-academy/FunASR] only generate 2 words (Issue #963)





 
Please provide detailed information so that we can reproduce the issue. If we cannot reproduce it, it means the problem cannot be resolved.

**Comment by hnluo** [comment]
Please provide your inference recipe
